/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devsegal.jserve;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class TestResponseHeaders {
   @Test(expected = ResponseStatusNullException.class)
   public void testConvertingResponseStatusToStringThrowsResponseStatusNullExceptionForNullStatus() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(null, 0, null, null);
      ResponseHeaders.convertResponseStatusToString(headers);
   }

   @Test
   public void testConvertingResponseStatusToStringReturnsValidStringForOneWordStatus() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(STATUS.OK, 0, null, null);
      assertEquals("OK", ResponseHeaders.convertResponseStatusToString(headers));
   }

   @Test
   public void testConvertingResponseStatusToStringReturnsValidStringForTwoWordStatus() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(STATUS.NOT_FOUND, 0, null, null);
      assertEquals("NOT FOUND", ResponseHeaders.convertResponseStatusToString(headers));
   }

   @Test(expected = ResponseStatusNullException.class)
   public void testConvertingResponseHeadersToStringThrowsResponseStatusNullExceptionForNullStatus() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(null, 0, null, null);
      ResponseHeaders.convertToString(headers);
   }

   @Test
   public void testConvertingResponseHeadersToStringReturnsValidStatusLine() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(STATUS.OK, 200, null, null);
      assertTrue(ResponseHeaders.convertToString(headers).startsWith("HTTP/1.1 200 OK\r\n"));
   }
}
