/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devsegal.jserve;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class TestResponseHeaders {
   @Test(expected = ResponseStatusNullException.class)
   public void testConvertingResponseStatusToStringThrowsResponseStatusNullExceptionForNullStatus() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(null, 0, null, null);
      ResponseHeaders.convertResponseStatusToString(headers);
   }

   @Test
   public void testConvertingResponseStatusToStringReturnsValidStringForTwoHundredOkStatus() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(STATUS.OK, 0, null, null);
      assertEquals("OK", ResponseHeaders.convertResponseStatusToString(headers));
   }

   @Test
   public void testConvertingResponseStatusToStringReturnsValidStringForMoreThanOneWordSeparatedByUnderscore() throws ResponseStatusNullException {
      ResponseHeaders headers = new ResponseHeaders(STATUS.NOT_FOUND, 0, null, null);
      assertEquals("NOT FOUND", ResponseHeaders.convertResponseStatusToString(headers));
   }
}
